name: "Teste de workflow - action"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  teste-action-job:
    runs-on: ubuntu-latest
    name: "Execução de actions"

    steps:
      - name: Adicionando comentário
        uses: Lucas-19sc/action-js@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issue-id: ${{ github.event.issue.number }}
          comment: "teste de comentario"